---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: docker-docker
    image: ubuntu:bionic
provisioner:
  name: ansible
  lint:
    name: ansible-lint
ansible:
  playbook: playbook.yml
scenario:
  name: default
lint:
  name: yamllint
verifier:
  name: testinfra
  env:
    # get rid of the DeprecationWarning messages of third-party libs,
    # see https://docs.pytest.org/en/latest/warnings.html#deprecationwarning-and-pendingdeprecationwarning
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  lint:
    name: flake8
